// Run only against a disposable localhost database and dedicated CDP browser.
import assert from 'node:assert/strict';
import { readFile,writeFile } from 'node:fs/promises';
const origin='http://localhost:3001';
const vars=Object.fromEntries((await readFile('.dev.vars','utf8')).trim().split('\n').map(l=>{const i=l.indexOf('=');return [l.slice(0,i),l.slice(i+1)]}));
const version=await (await fetch('http://localhost:9333/json/version')).json();const ws=new WebSocket(version.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let seq=0;const pending=new Map();ws.addEventListener('message',e=>{const data=JSON.parse(e.data);if(data.id){const p=pending.get(data.id);pending.delete(data.id);data.error?p.reject(new Error(JSON.stringify(data.error))):p.resolve(data.result)}});
function cdp(method,params={},sessionId){const id=++seq;return new Promise((resolve,reject)=>{pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params,...(sessionId?{sessionId}:{})}))})}
async function browser(){const {browserContextId}=await cdp('Target.createBrowserContext');const {targetId}=await cdp('Target.createTarget',{url:origin,browserContextId});const {sessionId}=await cdp('Target.attachToTarget',{targetId,flatten:true});await cdp('Page.enable',{},sessionId);await cdp('Runtime.enable',{},sessionId);await cdp('WebAuthn.enable',{},sessionId);const {authenticatorId}=await cdp('WebAuthn.addVirtualAuthenticator',{options:{protocol:'ctap2',transport:'internal',hasResidentKey:true,hasUserVerification:true,isUserVerified:true,automaticPresenceSimulation:true}},sessionId);const b={sessionId,authenticatorId,browserContextId};for(let i=0;i<60;i++){try{if(await evaluate(b,'location.origin')===origin)return b}catch{}await new Promise(r=>setTimeout(r,250))}throw new Error('Page did not load')}
async function evaluate(b,expression){const r=await cdp('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true},b.sessionId);if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||JSON.stringify(r.exceptionDetails));return r.result.value}
async function api(b,path,value,method=value===undefined?'GET':'POST'){return evaluate(b,`(async()=>{const r=await fetch(${JSON.stringify(path)}, {method:${JSON.stringify(method)},headers:{'Content-Type':'application/json'},${value===undefined?'':`body:${JSON.stringify(JSON.stringify(value))},`}});return {status:r.status,data:await r.json().catch(()=>null)}})()`)}
async function ceremony(b,email,code,expect=200){const path=code?'register':'login';const options=await api(b,`/api/auth/${path}/options`,{email,code});assert.equal(options.status,200,JSON.stringify(options.data));const cookies=await cdp('Network.getCookies',{urls:[origin]},b.sessionId);const challenge=cookies.cookies.find(c=>c.name==='tempo_challenge');const credential=await evaluate(b,`(async()=>{const o=${JSON.stringify(options.data)};const dec=s=>Uint8Array.from(atob(s.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0));o.challenge=dec(o.challenge);${code?"o.user.id=dec(o.user.id);o.excludeCredentials=o.excludeCredentials.map(c=>({...c,id:dec(c.id)}));return (await navigator.credentials.create({publicKey:o})).toJSON();":"o.allowCredentials=o.allowCredentials.map(c=>({...c,id:dec(c.id)}));return (await navigator.credentials.get({publicKey:o})).toJSON();"}})()`);const verified=await api(b,`/api/auth/${path}/verify`,credential);assert.equal(verified.status,expect,JSON.stringify(verified.data));return {verified,credential,challenge,path}}
const owner=await browser();let ids=[];
try{
 assert.equal((await api(owner,'/api/workspace')).status,401);assert.equal((await api(owner,'/api/session')).status,404);
 const registration=await ceremony(owner,vars.OWNER_EMAIL,vars.OWNER_SETUP_CODE);const ownerUser=registration.verified.data.user;ids.push(ownerUser.id);
 console.log('PASS: WebAuthn registration verifies inside the Cloudflare Worker runtime.');
 await cdp('Network.setCookie',{name:'tempo_challenge',value:registration.challenge.value,url:origin,httpOnly:true,sameSite:'Strict'},owner.sessionId);
 assert.equal((await api(owner,'/api/auth/register/verify',registration.credential)).status,401);
 const original=await api(owner,'/api/workspace');assert.equal(original.status,200);
 let snap=original.data;const unique='OWNER PRIVATE '+crypto.randomUUID();let updated=await api(owner,'/api/workspace',{action:'saveSettings',revision:snap.revision,payload:{name:unique,goal:40,currency:'USD'}});assert.equal(updated.status,200);
 const ownerCookie=(await cdp('Network.getCookies',{urls:[origin]},owner.sessionId)).cookies.find(c=>c.name==='tempo_session');
 assert.equal((await api(owner,'/api/auth/logout',{})).status,200);assert.equal((await api(owner,'/api/auth/me')).status,401);
 await cdp('Network.setCookie',{name:'tempo_session',value:ownerCookie.value,url:origin,httpOnly:true,sameSite:'Strict'},owner.sessionId);assert.equal((await api(owner,'/api/auth/me')).status,401);
 await ceremony(owner,vars.OWNER_EMAIL);assert.equal((await api(owner,'/api/auth/me')).data.role,'owner');
 const invited=await api(owner,'/api/admin/users',{email:'tempo-e2e-member@example.com'});assert.equal(invited.status,201);ids.push(invited.data.id);
 const member=await browser();assert.equal((await api(member,'/api/admin/users')).status,401);
 await ceremony(member,invited.data.email,invited.data.code);assert.equal((await api(member,'/api/admin/users')).status,403);
 const memberSnap=await api(member,'/api/workspace?userId='+ownerUser.id);assert.equal(memberSnap.status,200);assert.notEqual(memberSnap.data.workspace.name,unique);
 const changed=await api(member,'/api/workspace',{userId:ownerUser.id,action:'saveSettings',revision:memberSnap.data.revision,payload:{userId:ownerUser.id,name:'MEMBER ONLY',goal:30,currency:'CAD'}});assert.equal(changed.status,200);assert.equal((await api(owner,'/api/workspace')).data.workspace.name,unique);
 assert.equal((await api(owner,'/api/admin/users',{id:ownerUser.id},'DELETE')).status,400);
 const beforeRecovery=(await cdp('Network.getCookies',{urls:[origin]},member.sessionId)).cookies.find(c=>c.name==='tempo_session');const recovery=await api(owner,'/api/admin/users/reissue',{id:invited.data.id});assert.equal(recovery.status,200);
 assert.equal((await api(member,'/api/auth/me')).status,401);assert.equal((await api(member,'/api/auth/login/options',{email:invited.data.email})).status,401);
 await ceremony(member,invited.data.email,recovery.data.code);assert.equal((await api(member,'/api/workspace')).data.workspace.name,'MEMBER ONLY');
 await cdp('Network.setCookie',{name:'tempo_session',value:beforeRecovery.value,url:origin,httpOnly:true,sameSite:'Strict'},member.sessionId);assert.equal((await api(member,'/api/auth/me')).status,401);
 await ceremony(member,invited.data.email);assert.equal((await api(owner,'/api/admin/users',{id:invited.data.id},'DELETE')).status,200);assert.equal((await api(member,'/api/workspace')).status,401);
 const locked=await api(owner,'/api/admin/users',{email:'tempo-e2e-locked@example.com'});assert.equal(locked.status,201);ids.push(locked.data.id);for(let i=0;i<5;i++)assert.equal((await api(member,'/api/auth/register/options',{email:locked.data.email,code:'WRONG'})).status,401);assert.equal((await api(member,'/api/auth/register/options',{email:locked.data.email,code:locked.data.code})).status,401);
 const bootstrap=await api(owner,'/api/auth/register/options',{email:vars.OWNER_EMAIL,code:vars.OWNER_SETUP_CODE});assert.equal(bootstrap.status,401);
 // Authenticator counter regression: first login advances the counter, then rewind it.
 const stored=await cdp('WebAuthn.getCredentials',{authenticatorId:owner.authenticatorId},owner.sessionId);const passkey=stored.credentials[0];await cdp('WebAuthn.removeCredential',{authenticatorId:owner.authenticatorId,credentialId:passkey.credentialId},owner.sessionId);await cdp('WebAuthn.addCredential',{authenticatorId:owner.authenticatorId,credential:{...passkey,signCount:0}},owner.sessionId);await ceremony(owner,vars.OWNER_EMAIL,undefined,401);
 console.log('PASS: login, replay prevention, logout revocation, tenant isolation, owner-only admin, member recovery/removal, setup lockout, bootstrap single use, signature counter regression.');
 // Screenshot the actual sign-in UI at desktop and mobile sizes.
 await api(owner,'/api/auth/logout',{});await cdp('Page.navigate',{url:origin},owner.sessionId);await new Promise(r=>setTimeout(r,1500));const desktop=await cdp('Page.captureScreenshot',{format:'png'},owner.sessionId);await writeFile('/tmp/tempo-auth-desktop.png',Buffer.from(desktop.data,'base64'));await cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},owner.sessionId);const mobile=await cdp('Page.captureScreenshot',{format:'png'},owner.sessionId);await writeFile('/tmp/tempo-auth-mobile.png',Buffer.from(mobile.data,'base64'));
 console.log('Screenshots saved for sign-in UI review.');
}finally{await writeFile('/tmp/tempo-auth-cleanup.sql',ids.map(id=>`DELETE FROM workspaces WHERE id='${id}'; DELETE FROM users WHERE id='${id}';`).join('\n')+'\nDELETE FROM auth_limits;');await cdp('Browser.close');ws.close()}
